hello:
    path: /hello/{name}
    defaults:
        name: world
    controller: App\Controller\HelloController@sayHello

list:
    path: /
    controller: App\Controller\TaskController@index

create:
    path: /create
    controller: App\Controller\TaskController@create
    host: localhost
    schemes: ['http']
    methods: ['POST', 'GET']

show:
    path: /show/{id}
    controller: App\Controller\TaskController@show
    requirements:
        id: \d+
